modLoader = "javafml"
loaderVersion = "[36,)"
license = "All Rights Reserved"
issueTrackerURL = "http://Coros.us/"

[[mods]]
modId = "weather2remaster"
version = "${mod_version}"
displayName = "Weather 2 - Remastered"
authors = "Corosus, Mrbt0907, Fartsy"
credits = "A huge thanks to Corosus for developing the Weather 2 mod for all of us to enjoy."
description = '''
Brings a new localized weather system into your game, giving the environment around you more atmosphere while giving you storms to worry about.
'''

[[mods]]
modId = "coroutillegacy"
version = "${mod_version}"
displayName = "CoroUtilLegacy"
authors = "Corosus"
description = '''
Core utility library for Weather2 - Remastered
'''

[[mods]]
modId = "configex"
version = "${mod_version}"
displayName = "ConfigModEX"
authors = "Mrbt0907, Fartsy"
description = '''
expanded Config'''

[[mods]]
modId = "extendedrenderer"
version = "${mod_version}"
displayName = "Extended Renderer"
authors = "Corosus"
description = '''
Extended rendering utilities.
'''

# Dependencies for extendedrenderer
[[dependencies.extendedrenderer]]
modId = "forge"
mandatory = true
versionRange = "[36.2.34,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.extendedrenderer]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5]"
ordering = "NONE"
side = "BOTH"